-- ============================================
-- COMPLETE SQL SCRIPT FOR CLERK + SUPABASE
-- ============================================

-- STEP 1: Drop all existing policies
DROP POLICY IF EXISTS "trans_select" ON public.transactions;
DROP POLICY IF EXISTS "trans_insert" ON public.transactions;
DROP POLICY IF EXISTS "trans_update" ON public.transactions;
DROP POLICY IF EXISTS "trans_delete" ON public.transactions;

DROP POLICY IF EXISTS "sub_select" ON public.subscriptions;
DROP POLICY IF EXISTS "sub_insert" ON public.subscriptions;
DROP POLICY IF EXISTS "sub_update" ON public.subscriptions;
DROP POLICY IF EXISTS "sub_delete" ON public.subscriptions;

DROP POLICY IF EXISTS "goal_select" ON public.goals;
DROP POLICY IF EXISTS "goal_insert" ON public.goals;
DROP POLICY IF EXISTS "goal_update" ON public.goals;
DROP POLICY IF EXISTS "goal_delete" ON public.goals;

DROP POLICY IF EXISTS "budget_select" ON public.budgets;
DROP POLICY IF EXISTS "budget_insert" ON public.budgets;
DROP POLICY IF EXISTS "budget_update" ON public.budgets;
DROP POLICY IF EXISTS "budget_delete" ON public.budgets;

DROP POLICY IF EXISTS "task_select" ON public.tasks;
DROP POLICY IF EXISTS "task_insert" ON public.tasks;
DROP POLICY IF EXISTS "task_update" ON public.tasks;
DROP POLICY IF EXISTS "task_delete" ON public.tasks;

DROP POLICY IF EXISTS "inst_select" ON public.installments;
DROP POLICY IF EXISTS "inst_insert" ON public.installments;
DROP POLICY IF EXISTS "inst_update" ON public.installments;
DROP POLICY IF EXISTS "inst_delete" ON public.installments;

-- STEP 2: Drop existing tables (recreate with correct types)
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.subscriptions CASCADE;
DROP TABLE IF EXISTS public.goals CASCADE;
DROP TABLE IF EXISTS public.budgets CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.installments CASCADE;

-- STEP 3: Recreate all tables with user_id as TEXT (for Clerk)
CREATE TABLE public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  amount numeric NOT NULL,
  category text NOT NULL,
  merchant text,
  date date NOT NULL,
  note text,
  type text DEFAULT 'expense',
  account text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  name text NOT NULL,
  amount numeric NOT NULL,
  cycle text NOT NULL CHECK (cycle IN ('daily', 'weekly', 'monthly', 'yearly')),
  next_renewal date NOT NULL,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'cancelled')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  name text NOT NULL,
  target numeric NOT NULL,
  saved numeric NOT NULL DEFAULT 0,
  emoji text,
  deadline date,
  color text DEFAULT '#8B5CF6',
  monthly_contribution numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.budgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  category text NOT NULL,
  "limit" numeric NOT NULL,
  color text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  user_id text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.installments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  name text NOT NULL,
  amount numeric NOT NULL,
  total_months integer NOT NULL,
  paid_months integer NOT NULL DEFAULT 0,
  remaining_amount numeric NOT NULL,
  next_payment_date text NOT NULL,
  status text DEFAULT 'active' CHECK (status IN ('active', 'warning', 'completed')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- STEP 4: Enable RLS
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.installments ENABLE ROW LEVEL SECURITY;

-- STEP 5: Create policies with Clerk JWT (auth.jwt() ->> 'sub')
CREATE POLICY "trans_select" ON public.transactions FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "trans_insert" ON public.transactions FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "trans_update" ON public.transactions FOR UPDATE USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "trans_delete" ON public.transactions FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);

CREATE POLICY "sub_select" ON public.subscriptions FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "sub_insert" ON public.subscriptions FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "sub_update" ON public.subscriptions FOR UPDATE USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "sub_delete" ON public.subscriptions FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);

CREATE POLICY "goal_select" ON public.goals FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "goal_insert" ON public.goals FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "goal_update" ON public.goals FOR UPDATE USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "goal_delete" ON public.goals FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);

CREATE POLICY "budget_select" ON public.budgets FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "budget_insert" ON public.budgets FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "budget_update" ON public.budgets FOR UPDATE USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "budget_delete" ON public.budgets FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);

CREATE POLICY "task_select" ON public.tasks FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "task_insert" ON public.tasks FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "task_update" ON public.tasks FOR UPDATE USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "task_delete" ON public.tasks FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);

CREATE POLICY "inst_select" ON public.installments FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "inst_insert" ON public.installments FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "inst_update" ON public.installments FOR UPDATE USING (auth.jwt() ->> 'sub' = user_id);
CREATE POLICY "inst_delete" ON public.installments FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);
